# version: "3"
# services:
#   client:
#     image: "sanyamgupta23/multi-client"
#     mem_limit: 128m
#     hostname: client
#   server:
#     image: "sanyamgupta23/multi-server"
#     mem_limit: 128m
#     hostname: api
#     environment:
#       - REDIS_HOST=$REDIS_HOST
#       - REDIS_PORT=$REDIS_PORT
#       - POSTGRES_HOST=$POSTGRES_HOST
#       - POSTGRES_DATABASE_NAME
#       - POSTGRES_PASSWORD
#       - POSTGRES_USER
#       - POSTGRES_PORT
#   worker:
#     image: "sanyamgupta23/multi-worker"
#     mem_limit: 128m
#     hostname: worker
#     environment:
#       - REDIS_HOST=$REDIS_HOST
#       - REDIS_PORT=$REDIS_PORT
#   nginx:
#     image: "sanyamgupta23/multi-nginx"
#     mem_limit: 128m
#     hostname: nginx
#     ports:
#       - "80:80"
