name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build a test client image
        run: docker build -t sanyamgupta23/multi-aws-containers-test -f Dockerfile.dev ./client

      - name: Run tests in Docker
        run: docker run -e CI=true sanyamgupta23/multi-aws-containers-test npm test
